apiVersion: apps/v1
kind: Deployment
metadata:
  name: ac-1-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ac-lab-1
  template:
    metadata:
      labels:
        app: ac-lab-1
    spec:  
      containers:
      - name: ac-lab-1
        image: valeriafi191/cloud_app
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
