apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: ac-1-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ac-1-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
