name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    environment: dev
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GiHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Build with Gradle Wrapper
      run: ./gradlew bootJar

    - name: Set Docker Image Tag
      id: tag
      run: |
        latest_tag="latest"
        counter=$(docker image ls valeriafi191/cloud_app --format "{{ .Tag }}" | grep -oE '[0-9]+' | sort -nr | head -n1)
        if [ -z "$counter" ]; then
            counter=0
        fi
        ((counter++))
        tag="v$counter"
        echo "::set-output name=tag::$tag"

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: valeriafi191/cloud_app
        tags: ${{ steps.tag.outputs.tag }}, latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
